<div class="container">
	<h1>Listar Usuários</h1>

<table class="table table-hover table-striped">
	<thead class="thead-dark">
	<tr>
		<th>ID</th>
		<th>Nome</th>
		<th>Email</th>
		<th>Criado em</th>
		<th>Ações</th>
	</tr>
</thead>
	<tr>
		<?php
			foreach ($usuarios as $campo => $cada_usuario) {
				$id = $cada_usuario[0];
				echo '<tr>';
					echo "<td>{$id}</td>";
					echo "<td>{$cada_usuario[1]}</td>";
					echo "<td>{$cada_usuario[2]}</td>";
					echo "<td>{$cada_usuario[4]}</td>";
					echo "<td>";
					echo "<a href='/excluir-usuario?id={$id}'>Excluir</a>&nbsp;";
					echo "<a href='/editar-usuario?id={$id}'>Editar</a>";
					echo "</td>";
				echo '</tr>';
			}
		?>
	</tr>
</table>