<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<div class="container">
	<ul class="nav nav-tabs mt-3 mb-5">
		<li class="nav item">
			<a class="nav-link" href="/">HOME</a>
		</li>
		<li class="nav item">
			<a class="nav-link" href="/usuarios">Listar Usuários</a>
		</li>
		<li class="nav item">
			<a class="nav-link" href="/novo-usuario">Novo Usuário</a>
		</li>
	</ul>
</div>